services:
  backend:
    volumes:
      - .:/app
      - ~/.m2:/root/.m2  # cache do Maven entre rebuilds

  frontend:
    volumes:
      - ./interface-react:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - SPRING_PROFILES_ACTIVE=dev
      - REACT_APP_BACKEND_URL=http://localhost:8081
      - REACT_APP_FRONTEND_URL=http://localhost:3000
    command: npm start